export const CONFIG = {
  API_GATEWAY: "http://localhost:8888/api",
};

export const API = {
  LOGIN: "/identity/auth/token",
  INTROSPECT: "/identity/auth/introspect",
  LOGOUT: "identity/auth/logout",
  REFRESH_TOKEN: "identity/auth/refresh",
  REGISTRATION: "/identity/users/registration",
  USER_BY_ID: (userId) => `/identity/users/${userId}`,
  GET_ALL_USER: "/identity/users/all",
  GET_ALL_USER_STATUS: "/identity/users/status/all",
  CHANGE_USER_STATUS: "/identity/users/change-status",
  PROFILE_BY_USERID: (userId) => `/profile/users/get-by-user-id/${userId}`,
  CHANGE_PASSWORD: "identity/users/change-password",
  MY_INFO: "/identity/users/my-info",
  MY_PROFILE: "/profile/users/my-profile",
  USER_SEARCH: "profile/search",
  MY_PROJECT: "/project/my-projects",
  PROJECT_BY_ID: (projectId) => `/project/${projectId}`,
  CREATE_PROJECT: "/project/create",
  LEAVE_PROJECT: "/project/member/leave-project",
  GET_MEMBERS: "project/member/get-members",
  ADD_MEMBER: "project/member/add",
  MEMBER_BY_ID: (memberId) => `/project/member/${memberId}`,
  MEMBER_SEARCH: "project/member/search",
  PROJECT_ROLE_ALL: "/project/roles/all",
  MY_TASK: "/task/my-tasks",
  TASK_IN_PROJECT: "/task/all-in-project",
  TASK_BY_ID: (taskId) => `/task/${taskId}`,
  CHANGE_TASK_STATUS: (taskId) => `/task/${taskId}/change-status`,
  ASSIGN_TASK: (taskId) => `/task/${taskId}/assign`,
  UNASSIGN_TASK: (taskId) => `/task/${taskId}/unassign`,
  TASK_CREATE: "/task/create",
  TASK_STATUS_ALL: "/task/status/all",
  MY_NOTIFICATION: "/notification/my-notifications",
  REPORT: "/report/report-project",
};
