server:
  port: 8085
  servlet:
    context-path: /comment
spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://root:passroot@localhost:27017/comment-service?authSource=admin
app:
  services:
    profile: http://localhost:8081/profile